spring:
  application:
    name: Easeplan
  datasource:
    url: jdbc:mysql://localhost:3306/EasePlan?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: hslj
    password: hslj1920!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
